### ISSUE TITLE
phosphor-ipmi-flash does not have a MAINTAINERS file

### ISSUE THREAD

**Issue by bradbishop** [openbmc/phosphor-ipmi-flash#1]
Please add a maintainers file.  Here is an example https://github.com/openbmc/phosphor-hwmon/blob/master/MAINTAINERS

**Comment by pstrinkle** [comment]
The MAINTAINERS file is being added in https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-ipmi-flash/+/11623/ presently, however, if you want I can pull it into a separate patchset.

**Comment by bradbishop** [comment]
@pstrinkle thanks!
