### ISSUE TITLE
Unable to build phosphor-ipmi-flash

### ISSUE THREAD

**Issue by sujoyray** [openbmc/phosphor-ipmi-flash#3]
Hello,
I am getting the following error:
make[2]: Leaving directory '/home/sujoy/phosphor_ipmi_flash/phosphor-ipmi-flash'
Making all in tools
make[2]: Entering directory '/home/sujoy/phosphor_ipmi_flash/phosphor-ipmi-flash/tools'
Making all in .
make[3]: Entering directory '/home/sujoy/phosphor_ipmi_flash/phosphor-ipmi-flash/tools'
  CXX      burn_my_bmc-main.o
In file included from main.cpp:20:
net.hpp:11:10: fatal error: stdplus/handle/managed.hpp: No such file or directory
   11 | #include <stdplus/handle/managed.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Below is the description of my setup:
1) OS: Ubuntu 19.10
2) GCC version: gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

What I have done: 
Step 1: Built the pciutils by following steps:
make SHARED=**no**    [instruction says yes]
make SHARED=**no** install
make install-lib

Step 2: Built the  ipmi-blob-tool
./bootstrap.sh
./configure --disable-tests
make
make install

Step 3: built burn_my_bmc
./bootstrap.sh
./configure --disable-build-bmc-blob-handler
make
make install

I got the error during make stage.

Any help will be greatly appreciated.
Thank you.
Sujoy.

**Comment by brandonkimbk** [comment]
Hi Sujoy, which "make" stage did you fail at? Was it for all 3 steps? or just for the last step for "burn_my_bmc"?

**Comment by sujoyray** [comment]
Hi Brandon,
It failed at the last step for burn_my_bmc.
Thank you.
Sujoy.

**Comment by brandonkimbk** [comment]
Hi Sujoy,

I'm sorry, I somehow didn't get notified that you commented on this issue. It looks like for some reason, stdplus library isn't being included in your build... I'll try building it from my system and update you on the issue.

**Comment by sujoyray** [comment]
Hello Brandon,
No – problem. Please try to build from scratch in a clean folder / system. You would be able to reproduce the issue.
Thank you for looking into this…
Sujoy

**Comment by brandonkimbk** [comment]
Hi Sujoray, my apologies for another delayed response - I had a cycling accident last week and have not been at full capacity.

I was able to reproduce this error on a clean environment, let me see how I can fix this.

**Comment by brandonkimbk** [comment]
Looks like I was able to fix the dependency by installing the stdplus library: https://github.com/openbmc/stdplus

I noticed that the installation step for that library is outdated as it now uses meson build. I will send out a code review to update their README doc. In the mean time, please install meson using https://mesonbuild.com/Installing.html and then build the library using `meson builddir` from the cloned repo of stdplus, then install the library by going to builddir using `cd builddir` then `meson install` .

I had a few more linker problems complaining about -lpci, which I was able to solve by following https://github.com/matszpk/amdcovc/issues/10

**Comment by brandonkimbk** [comment]
I'll update the README file for this repository with the updated steps as well, thanks for pointing this out Sujoy!

**Comment by brandonkimbk** [comment]
Code review is in progress here: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-ipmi-flash/+/29146
