### ISSUE TITLE
configure error conditional "XXX" was never defined. 

### ISSUE THREAD

**Issue by kiwi0217** [openbmc/phosphor-ipmi-flash#8]
When I completed all setting and start to install phosphor-ipmi-flash.

After execute "./configure --disable-build-bmc-blob-handler".
It returns as following message on the shell:

configure: error: conditional "HAVE_SYSTEMUNITDIR" was never defined.
Usually this means the macro was only invoked conditionally

I have no idea what's going on.
Please helps, thanks.

**Comment by kiwi0217** [comment]
It can solved by reset to version "c78bfc823049e96522eaab333d74d16c7efd6917"
Newest can not build in Ubuntu18

**Comment by brandonkimbk** [comment]
Apologies, I missed this issue. Do you still see this issue?

**Comment by viarand** [comment]
Fixed merged: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-ipmi-flash/+/46243
