### ISSUE TITLE
fail to build stdplus with the command in README.md

### ISSUE THREAD

**Issue by medadyoung** [openbmc/phosphor-ipmi-flash#9]
Hi,
when I am building stdplus, I met following error. 
please help.
thanks in advance. 

ninja: Entering directory `builddir'
[1/1] Linking target src/libstdplus.so.0.1
FAILED: src/libstdplus.so.0.1
c++  -o src/libstdplus.so.0.1 src/libstdplus.so.0.1.p/stdplus_exception.cpp.o src/libstdplus.so.0.1.p/stdplus_signal.cpp.o src/libstdplus.so.0.1.p/stdplus_dl.cpp.o src/libstdplus.so.0.1.p/stdplus_fd_create.cpp.o src/libstdplus.so.0.1.p/stdplus_fd_dupable.cpp.o src/libstdplus.so.0.1.p/stdplus_fd_impl.cpp.o src/libstdplus.so.0.1.p/stdplus_fd_managed.cpp.o src/libstdplus.so.0.1.p/stdplus_fd_ops.cpp.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libstdplus.so.0 /usr/local/lib/libfmt.a -ldl -Wl,--end-group
/usr/bin/ld: /usr/local/lib/libfmt.a(format.cc.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by brandonkimbk** [comment]
Hi, apologies for getting back to you so late.

Are you stilling having trouble? Is this the step while you're building stdplus? https://github.com/openbmc/phosphor-ipmi-flash#building-stdplus

**Comment by medadyoung** [comment]
Hi,
Thanks for your reply.
There is no trouble on stdplus now.
Thanks

B.R.
medad


Brandon Kim ***@***.***> 於 2022年3月5日 週六 上午4:52 寫道：

**Comment by brandonkimbk** [comment]
Awesome! Closing the issue.
